<html>
<head>

<style type="text/css">
body {
	font-family: sans-serif;
}

table {
	page-break-inside:avoid;
	border-collapse: collapse;
	border:1px solid #ccc;
}
th, td {
	border:1px solid #ccc;
	padding: 3px;
	text-align: left;
}
</style>
</head>

<body>

<div id="presenterDetails">
<?php echo $this->contents['presenterDetails']; ?>
</div>
<br/>
<div id="surveySummaries">
<?php echo $this->contents['surveySummaries']; ?>
</div>

</body>
</html>
