<div class="btn-group span1 year_section" data-toggle="buttons-radio" id="pyear-buttons">
	<button type="button" class="btn" id="p3" value="3">P3</button>
	<button type="button" class="btn" id="p4" value="4">P4</button>
</div>

<div class="btn-group span4 year_section" data-toggle="buttons-radio" id="section-buttons">
	<button type="button" class="btn" id="s1" value="1">Section 1</button>
	<button type="button" class="btn" id="s2" value="2">Section 2</button>
	<button type="button" class="btn" id="s3" value="3">Section 3</button>
	<button type="button" class="btn" id="s4" value="4">Section 4</button>
	<button type="button" class="btn" id="s5" value="5">Section 5</button>
</div>


