<?php echo $this->doctype(); ?>

<html>

<head>

<?php echo $this->headMeta() ?>

<?php echo $this->headTitle('Seminar Grading System') ?>


<?php echo $this->headStyle() ?>

<?php echo $this->headLink()
	->appendStylesheet('//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/css/bootstrap-combined.min.css')
	->appendStylesheet('/css/bootstrap-responsive.css')
	->appendStylesheet('/css/fixed-layout.css')
	->appendStylesheet('css/userTable.css');
?>


<?php echo $this->headScript()->appendFile(
		'http://html5shim.googlecode.com/svn/trunk/html5.js',
		'text/javascript',
		array('conditional'=>'lt IE 9')
	);
?>

	
</head>

<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Seminar Grading</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><a href="/">Home</a></li>
		  <li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/user">View Users</a></li>
              <li><a href="/user/create-user">Create a user</a></li>
              <li><a href="/user/edit-user">Edit a user</a></li>
            </ul>
          </li>
          <li><a href="/section">Section Builder</a></li>
          <li><a href="/attendance">Attendance</a></li>
          <li><a href="/grading">Grading</a></li>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar-inner -->
</div><!-- /.navbar -->

<div class="container">
	<?php echo $this->layout()->content; ?>
</div>

<?php echo $this->inlineScript()
	->appendFile('http://code.jquery.com/jquery-1.8.1.min.js')
	->appendFile('http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/js/bootstrap.min.js')
	->appendFile('/js/jquery.dataTables.min.js')
	->appendFile('/js/userTable.js');
?>

</body>

</html>
