<?php echo $this->doctype(); ?>

<html>

<head>

<?php echo $this->headMeta() ?>

<?php echo $this->headTitle('Seminar Grading System') ?>


<?php echo $this->headStyle() ?>

<?php echo $this->headLink()
	//->appendStylesheet('//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/css/bootstrap-combined.min.css')
	->appendStylesheet('/css/bootstrap.min.css')
	->appendStylesheet('/css/bootstrap-responsive.css')
	->appendStylesheet('/css/fixed-layout.css')
	->appendStylesheet('/css/userTable.css')
	->appendStylesheet('/css/custom-theme/jquery-ui-1.8.23.custom.css');
?>


<?php echo $this->headScript()->appendFile(
		'http://html5shim.googlecode.com/svn/trunk/html5.js',
		'text/javascript',
		array('conditional'=>'lt IE 9')
	);
?>

	
</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Seminar Grading</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><a href="/">Home</a></li>
		  <li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/user">View Users</a></li>
              <li><a href="/user/create-user">Create a user</a></li>
            </ul>
          </li>
          <!--<li><a href="/section">Section Builder</a></li>-->
          <li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Grading <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/grading">Seminar Grading Tool</a></li>
              <li><a href="/grading/report">Reports</a></li>
              <li><a href="/upload/survey">Upload Seminar Survey Data</a></li>
            </ul>	
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar-inner -->
</div><!-- /.navbar -->

<div class="container">
	<?php echo $this->layout()->content; ?>
</div>
<?php echo $this->inlineScript()
	->appendFile('http://code.jquery.com/jquery-1.8.1.min.js')
	->appendFile('/js/jquery-ui-1.8.23.custom.min.js')
	->appendFile('/js/jquery.jeditable.min.js')
	->appendFile('/js/bootstrap.min.js')
	->appendFile('/js/jquery.dataTables.min.js')
	->appendFile('/js/userTable.js')
	->appendFile('/js/uploadTools.js')
	->appendFile('/js/gradingTools.js');
?>

</body>

</html>
