<div class="row">

	<div class="span12">
		<h1>Reset the Grading Database</h1>

	

		<div class="row">
			<div class="span6">
				<? echo $this->resetForm; ?>

			</div>

			<div class="span6">
				<h4>Instructions:</h4>
				<ul>
					<li>Click the 'Reset Database' button to clear the database and reset the section configurations for the to the current academic year.</li>
					<li>This action will generate an archive of all data curently in the database, much like the <a href="/seminars/archive">Archive</a> tool.</li>
					<li>This action will destroy all data in the database.</li>
					<li>Click the 'Download archive' link to retrieve the current archive.</li>
				</ul

			</div>

		</div>	

	</div>

</div>

