<?php
if(isset($this->error)) {
	$message = 'An error occurred while updating your user:<br/>' . $this->error->getMessage();
} elseif($this->message == 'success') {
	$message = 'User sucessfully edited.';
}

?>


<h1>Edit User</h1>
<?php if(isset($message)): ?>
<p>
<?php if(isset($message)) { echo $message; } ?>
</p>
<?php endif; ?>


<?php
echo $this->editUserForm;
?>
<?php if(isset($this->updatedUser)): ?>
<p>
<?php //print_r($this->updatedUser); ?>
</p>
<?php endif; ?>
