<h1>User Manager</h1>
<?php
?>

<div class="container" style="margin-top: 10px">
<table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="userTable">
	<caption></caption>
	<colgroup />
	<colgroup span="2" title="title" />
	<thead>
		<tr>
			<th scope="col">unid</th>
			<th scope="col">First Name</th>
			<th scope="col">Last Name</th>
			<th scope="col">Email</th>
			<th scope="col">Role</th>
			<!--<th scope="col">Created</th>-->
			<!--<th scope="col">Updated</th>-->
			<th scope="col">Tools</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
		</tr>
	</tfoot>
	<tbody>
<?php foreach(json_decode($this->users) as $user): ?>
	<tr>
		<td><?php echo $user->unid; ?></td>
		<td><?php echo $user->first_name; ?></td>
		<td><?php echo $user->last_name; ?></td>
		<td><?php echo $user->email; ?></td>
		<td><?php echo $user->roles[0]->title; ?></td>
		<!--<td><?php echo $user->created_date; ?></td>-->
		<!--<td><?php echo $user->updated; ?></td>-->
		<td>
			<a href="/user/edit-user?user_id=<?php echo $user->id; ?>">edit</a>
		</td>
	</tr>
<?php endforeach; ?>
	</tbody>
</table>
</div>

