<h2>Initialize Sections for an Academic Year</h2>



<div class="span8">

<h4>Current Academic Year: <?php echo $this->currentAcademicYear['year']; ?></h4>

<p>
Use this form to initialize the section structure for the current academic year.
</p>

<?php echo $this->initSectionsForm; ?>

<?php echo $this->message; ?>

<p>Be Advised:</p>
<ul>
<li>For an academic year other than the current academic year you must first add the year using the <a href="/seminars/section/academic-year-settings">Academic Year Settings</a> tool.</li>
<li>This tool will not delete data or change the current academic year setting. It will only add section mapping data to the appropriate table in the database.</li>
</ul>


</div>

